#ifndef DEFINES_H_
#define DEFINES_H_

#define NULL 0
#define BACKGROUND_COLOR 0xff222222
#define POINT_COLOR 0xff0000ff
#define AABB_BORDER_COLOR 0xfff0f0f0

#define SCREEN_WIDTH 832
#define SCREEN_HEIGHT 832

#define HALF_WIDTH SCREEN_WIDTH / 2
#define HALF_HEIGHT SCREEN_HEIGHT / 2

#define GRID_LENGTH 13
#define GRID_SIZE 64

#define PLAYER_SPEED 550

#define MAX_FIRE_LINE GRID_LENGTH

#define BOMB_DELAY_TICK 120

#define BOMB_NORMAL_TICKS 25
#define FIRE_NORMAL_TICKS 35

#endif // DEFINES_H_
